### ISSUE TITLE
Will I get banned?

### ISSUE THREAD

**Issue by Burak35Smoke** [b0kch01/valorant-cheat#1]
Is there a ban?

**Comment by b0kch01** [comment]
It should still work. Ban is unlikely but **I wouldn't recommend using it in a real game** anyways. There's always a chance they can ban you.

**Comment by kallefrombosnia** [comment]
They probably detect something regarding graphic capture since that is handled by python lib which probably hooks some Win functions (easy hook detection).
Didn't analyze it fully, but those are my 2 cents here.

**Comment by b0kch01** [comment]
> They probably detect something regarding graphic capture since that is handled by python lib which probably hooks some Win functions (easy hook detection). Didn't analyze it fully, but those are my 2 cents here.

I do agree that it is easy to detect but I am unsure if VANGUARD is able to differentiate between other screen recording/streaming software that is allowed.

**Comment by puryippap** [comment]
Haven't been banned, probably yet, but it's nice. While not amazingly, it still works in scenarios. When you're holding a corner and don't believe in your aim, maybe you're drinking water or just not as focused, you can hold an angle and still get a kill.

Are there any estimates on how long this will be stable for until it's immediately detected?

**Comment by b0kch01** [comment]
Glad you got it working. 

When will it be detected (or is it currently detected) by Vanguard? I have zero clue.

**Comment by puryippap** [comment]
Not playing any excuses or anything, I did, for the right reasons, get banned. I had used it actively for the past 2 or so days. It was pretty cool to experience, and I feel stupid as expected.
![image](https://user-images.githubusercontent.com/92653199/144706011-cf9451a8-6dba-4255-b91b-bf30f3c52b93.png)

**Comment by ItsChasa** [comment]
was gonna try this, but it seems its detected. thanks for letting everyone know :)

**Comment by iHafez** [comment]
there's no cheat cant be detected with vanguard (valorant anti cheat) it is just a matter of tim

**Comment by b0kch01** [comment]
Thanks for reporting 😊! And of course, _thanks to everyone else who commented along the way._ 
I will consider **this cheat detected.**

 It was fun while it lasted—~9 months under the radar—not too bad of a lifetime.

**Comment by iHafez** [comment]
bro it's detected since i said it is lol

**Comment by AbhayRog** [comment]
wait there is one more stand up for this project.... @iHafez did you use the exe or ran the python script? I believe if we run the script from cmd we wont get ban.... correct if Iam wrong.

**Comment by iHafez** [comment]
I ran it from python, also it doesn't matter lol
